services:
  moodle:
    image: my-moodle:latest
    container_name: moodle_app
    restart: always
    ports:
      - "8080:80"
    environment:
      MOODLE_DATABASE_TYPE: mariadb
      MOODLE_DATABASE_HOST: db
      MOODLE_DATABASE_PORT_NUMBER: 3306  # Fixed typo here
      MOODLE_DATABASE_NAME: moodle
      MOODLE_DATABASE_USER: moodle
      MOODLE_DATABASE_PASSWORD: "SafeP@ssw0rd-123"
      MOODLE_USERNAME: admin
      MOODLE_PASSWORD: "SecureAdminP@ssw0rd456"
      MOODLE_EMAIL: contact@rifaterdemsahin.com
      MOODLE_SITE_NAME: "Moodle LMS"
      MOODLE_HOST: "localhost"
      PHP_MAX_EXECUTION_TIME: 300
      PHP_MEMORY_LIMIT: 256M
      PHP_POST_MAX_SIZE: 50M
      PHP_UPLOAD_MAX_FILESIZE: 50M
      BITNAMI_DEBUG: "true"
    volumes:
      - moodle_data:/bitnami/moodle
      - moodledata_data:/bitnami/moodledata
    depends_on:
      - db
    networks:
      - moodle-net
    command: >
          bash -c "if [ ! -f /bitnami/moodle/config.php ]; then /opt/bitnami/scripts/moodle/entrypoint.sh /opt/bitnami/scripts/moodle/run.sh; else php /bitnami/moodle/admin/cli/install_database.php && /opt/bitnami/scripts/moodle/run.sh; fi"

  db:
    image: mariadb:10.6
    container_name: moodle_db
    restart: always
    environment:
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: "SafeP@ssw0rd-123"
      MYSQL_ROOT_PASSWORD: "RootP@ssw0rd789"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - moodle-net
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  moodle_data:
  moodledata_data:
  db_data:

networks:
  moodle-net:
    driver: bridge