services:
  moodle:
    image: my-moodle:latest
    container_name: moodle_app
    restart: no  # Change to "always" after success
    ports:
      - "8080:80"
    environment:
      MOODLE_DATABASE_TYPE: mysqli
      MOODLE_DATABASE_HOST: moodle_db
      MOODLE_DATABASE_PORT_NUMBER: 3306
      MOODLE_DATABASE_NAME: moodle
      MOODLE_DATABASE_USER: moodle
      MOODLE_DATABASE_PASSWORD: moodle
      MOODLE_USERNAME: admin
      MOODLE_PASSWORD: admin123
      MOODLE_EMAIL: admin@example.com
      MOODLE_SITE_NAME: "Moodle LMS"
      ALLOW_EMPTY_PASSWORD: "yes"
      MOODLE_SKIP_BOOTSTRAP: "no"
      MOODLE_HOST: localhost
      MOODLE_INSTALL_TIMEOUT: 1800
      MOODLE_DEBUG: "yes"
      PHP_MAX_EXECUTION_TIME: 600
      PHP_MEMORY_LIMIT: 512M
      PHP_POST_MAX_SIZE: 100M
      PHP_UPLOAD_MAX_FILESIZE: 100M
      PHP_LOG_ERRORS: "1"
      PHP_DISPLAY_ERRORS: "1"
    volumes:
      - moodle_data:/bitnami/moodle
      - moodledata_data:/bitnami/moodledata
      - ./php-logs:/opt/bitnami/php/logs
    depends_on:
      db:
        condition: service_healthy
    command: bash -c "sleep 15 && /opt/bitnami/scripts/moodle/entrypoint.sh /opt/bitnami/scripts/moodle/run.sh"

  db:
    image: mysql:5.7
    container_name: moodle_db
    environment:
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: moodle
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-umoodle", "-pmoodle", "-e", "SHOW DATABASES;"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  moodle_data:
  moodledata_data:
  db_data: