version: '3'

services:
  db:
    image: mysql:5.7
    container_name: moodle_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: moodle
    volumes:
      - moodle_db_data:/var/lib/mysql
    networks:
      - moodle_network
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  moodle:
    image: bitnami/moodle:4.3.3  # Pin a specific version
    container_name: moodle_app
    ports:
      - "8080:80"
    environment:
      MOODLE_DATABASE_TYPE: mysqli
      MOODLE_DATABASE_HOST: db
      MOODLE_DATABASE_PORT_NUMBER: 3306
      MOODLE_DATABASE_NAME: moodle
      MOODLE_DATABASE_USER: moodle
      MOODLE_DATABASE_PASSWORD: moodle
      MOODLE_USERNAME: admin
      MOODLE_PASSWORD: admin123
      MOODLE_EMAIL: admin@example.com
      MOODLE_SITE_NAME: Moodle LMS
      ALLOW_EMPTY_PASSWORD: "yes"
      MOODLE_SKIP_BOOTSTRAP: "no"
      MOODLE_HOST: localhost
      MOODLE_INSTALL_TIMEOUT: 1800  # Increased timeout
      PHP_MAX_EXECUTION_TIME: 600
      PHP_MEMORY_LIMIT: 512M
      PHP_POST_MAX_SIZE: 100M
      PHP_UPLOAD_MAX_FILESIZE: 100M
    volumes:
      - moodle_data:/bitnami/moodle
      - moodledata_data:/bitnami/moodledata
    depends_on:
      db:
        condition: service_healthy
    networks:
      - moodle_network
    restart: always

networks:
  moodle_network:
    driver: bridge

volumes:
  moodle_db_data:
  moodle_data:
  moodledata_data: