version: '3'

services:
  moodle:
    image: my-moodle:latest  # Custom image to fix Apache conf issue
    container_name: moodle_app
    restart: no  # Set to "always" in production after confirming it works
    ports:
      - "8080:80"
    environment:
      MOODLE_DATABASE_TYPE: mysqli
      MOODLE_DATABASE_HOST: moodle_db
      MOODLE_DATABASE_PORT_NUMBER: 3306
      MOODLE_DATABASE_NAME: moodle
      MOODLE_DATABASE_USER: moodle
      MOODLE_DATABASE_PASSWORD: moodle
      MOODLE_USERNAME: admin
      MOODLE_PASSWORD: admin123
      MOODLE_EMAIL: admin@example.com
      MOODLE_SITE_NAME: "Moodle LMS"
      ALLOW_EMPTY_PASSWORD: "yes"  # For dev only; remove in production
      MOODLE_SKIP_BOOTSTRAP: "no"
      MOODLE_HOST: localhost
      MOODLE_INSTALL_TIMEOUT: 1800
      MOODLE_DEBUG: "yes"
      PHP_MAX_EXECUTION_TIME: 600
      PHP_MEMORY_LIMIT: 512M
      PHP_POST_MAX_SIZE: 100M
      PHP_UPLOAD_MAX_FILESIZE: 100M
      PHP_LOG_ERRORS: "1"  # Enable PHP error logging
      PHP_DISPLAY_ERRORS: "1"  # Show errors in output
    volumes:
      - moodle_data:/bitnami/moodle
      - moodledata_data:/bitnami/moodledata
    depends_on:
      db:
        condition: service_healthy  # Wait for DB to be ready

  db:
    image: mysql:5.7
    container_name: moodle_db
    environment:
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: moodle
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  moodle_data:
  moodledata_data:
  db_data: