services:
  db:
    image: mysql:5.7
    container_name: moodle_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: moodle
    volumes:
      - moodle_db_data:/var/lib/mysql
    restart: always

  moodle:
    image: moodlehq/moodle-php-apache:8.0
    container_name: moodle_app
    ports:
      - "8080:80"
    environment:
      MOODLE_DB_TYPE: mysqli
      MOODLE_DB_HOST: db
      MOODLE_DB_NAME: moodle
      MOODLE_DB_USER: moodle
      MOODLE_DB_PASSWORD: moodle
      MOODLE_WWWROOT: http://localhost:8080
      MOODLE_ADMIN_USER: admin
      MOODLE_ADMIN_PASSWORD: admin123
      MOODLE_FULLNAME: "Moodle LMS"
      MOODLE_SHORTNAME: "Moodle"
    volumes:
      - moodle_data:/var/www/moodledata
    depends_on:
      - db
    restart: always

volumes:
  moodle_db_data:
  moodle_data: