version: '3'

services:
  db:
    image: mysql:5.7
    container_name: moodle_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: moodle
    volumes:
      - moodle_db_data:/var/lib/mysql
    networks:
      - moodle_network
    restart: always

  moodle:
    image: bitnami/moodle:latest
    container_name: moodle_app
    ports:
      - "8080:80"  # Changed from 8080:8080 to 8080:80
    environment:
      # Database configuration
      - MOODLE_DATABASE_TYPE=mysqli
      - MOODLE_DATABASE_HOST=db
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_NAME=moodle
      - MOODLE_DATABASE_USER=moodle
      - MOODLE_DATABASE_PASSWORD=moodle
      
      # Moodle configuration
      - MOODLE_USERNAME=admin
      - MOODLE_PASSWORD=admin123
      - MOODLE_EMAIL=admin@example.com
      - MOODLE_SITE_NAME=Moodle LMS
      
      # Required for GitHub Codespaces/Cloud IDE environments
      - ALLOW_EMPTY_PASSWORD=yes
      - MOODLE_SKIP_BOOTSTRAP=no
      - MOODLE_HOST=localhost:8080
      
      # Install timeout increase
      - MOODLE_INSTALL_TIMEOUT=1200
      
      # PHP configuration
      - PHP_MAX_EXECUTION_TIME=600
      - PHP_MEMORY_LIMIT=512M
      - PHP_POST_MAX_SIZE=100M
      - PHP_UPLOAD_MAX_FILESIZE=100M
    volumes:
      - moodle_data:/bitnami/moodle
      - moodledata_data:/bitnami/moodledata
    depends_on:
      - db
    networks:
      - moodle_network
    restart: always

networks:
  moodle_network:
    driver: bridge

volumes:
  moodle_db_data:
  moodle_data:
  moodledata_data: