version: '3.8'

services:
  moodle:
    image: my-moodle:latest
    container_name: moodle_app
    restart: always  # Automatic restarts for uptime
    ports:
      - "80:80"  # Standard HTTP port (or 443 with SSL)
    environment:
      MOODLE_DATABASE_TYPE: mysqli
      MOODLE_DATABASE_HOST: moodle_db
      MOODLE_DATABASE_PORT_NUMBER: 3306
      MOODLE_DATABASE_NAME: moodle
      MOODLE_DATABASE_USER: moodle
      MOODLE_DATABASE_PASSWORD: "StrongP@ssw0rd123"  # Secure password
      MOODLE_USERNAME: admin
      MOODLE_PASSWORD: "SecureAdminP@ssw0rd456"  # Strong admin password
      MOODLE_EMAIL: contact@rifaterdemsahin.com
      MOODLE_SITE_NAME: "Moodle LMS"
      MOODLE_SKIP_BOOTSTRAP: "no"  # Install once, then set to "yes"
      MOODLE_HOST: "rifaterdemsahin.com"  # Replace with actual domain
      MOODLE_INSTALL_TIMEOUT: 1800
      MOODLE_DEBUG: "no"  # Disable debugging in prod
      PHP_MAX_EXECUTION_TIME: 300  # Lower for efficiency
      PHP_MEMORY_LIMIT: 256M  # Adjust based on needs
      PHP_POST_MAX_SIZE: 50M
      PHP_UPLOAD_MAX_FILESIZE: 50M
      PHP_LOG_ERRORS: "1"  # Log errors, but don’t display
      PHP_DISPLAY_ERRORS: "0"  # Hide errors from users
    volumes:
      - moodle_data:/bitnami/moodle
      - moodledata_data:/bitnami/moodledata
    depends_on:
      - db
    deploy:  # Optional resource limits for production
      resources:
        limits:
          cpus: "1.0"
          memory: 1G

  db:
    image: mariadb:10.6
    container_name: moodle_db
    environment:
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: "StrongP@ssw0rd123"  # Match Moodle’s password
      MYSQL_ROOT_PASSWORD: "RootP@ssw0rd789"  # Secure root password
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-umoodle", "-pStrongP@ssw0rd123", "-e", "SHOW DATABASES;"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  moodle_data:
  moodledata_data:
  db_data: